import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { TooltipProvider } from "@radix-ui/react-tooltip";

const geistSans = localFont({
  src: "./(fonts)/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./(fonts)/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigation = [
    { name: "Home", href: "/" },
    { name: "Student", href: "/master/student" },
    { name: "Subject", href: "/master/subject" },
    { name: "Study Group", href: "/master/study-group" },
    { name: "Report", href: "/report" },
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          {children}
          </TooltipProvider>
      </body>
    </html>
  );
}
